server:
  port: 8081 # Porta interna do container

spring:
  application:
    name: micro-company
  datasource:
    url: jdbc:postgresql://postgres:5432/company_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Em produção, use Flyway/Liquibase
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configurações do RabbitMQ
spring.rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest