# A linha "version" não é mais necessária e foi removida.

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=company_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - micro-network

  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - micro-network

  config-server:
    build:
      # Mantém a versão corrigida com a variável de ambiente.
      context: ${PROJECT_ROOT}/infra/config-server
      args:
        - CONFIG_REPO_PATH=${PROJECT_ROOT}/infra/config-server/config-repo # Ajustado para a nova localização
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - micro-network

  eureka-server:
    build:
      # AJUSTE: Usa a variável de ambiente para garantir o caminho absoluto.
      context: ${PROJECT_ROOT}/infra/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - micro-network

  micro-company:
    build:
      # AJUSTE: Usa a variável de ambiente para garantir o caminho absoluto.
      context: ${PROJECT_ROOT}/micro-company
    container_name: micro-company
    ports:
      - "8081:8081"
    networks:
      - micro-network
    depends_on:
      - postgres
      - eureka-server
      - config-server

volumes:
  postgres_data:

networks:
  micro-network:
    driver: bridge