eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8081
spring:
  application:
    name: microcompany
  config:
    import: "configserver:"
