spring:
  application:
    name: eureka-server
server:
  port: 8761

# Configurações do Eureka Server
eureka:
  client:
    # O servidor não deve se registrar com ele mesmo
    register-with-eureka: false
    # O servidor não busca o registro de outros lugares, ele É o registro
    fetch-registry: false